name: 'Dependabot for Clojure projects'
author: 'Luigi Gubello'
description: 'Run Dependabot as GitHub Action workflow in your Clojure projects.'
branding:
  icon: 'shield'
  color: 'gray-dark'
inputs:
  auto_pull_request:
    description: 'Create auto pull-requests when updates for primary dependencies are available.'
    required: false
    default: true
  security_updates_only:
    descrition: 'Update only vulnerable packages.'
    required: false
    default: true
  update_omitted:
    descrition: '[Unstable] Update omitted packages.'
    required: false
    default: false
  severity:
    descrition: 'Minimum severity to update. Values: low, medium, high, critical.'
    required: false
    default: 'low'
  main_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: 'main'
  labels:
    description: 'Add labels to the pull-requests. Separate items by comma.'
    required: false
    default: ''
  reviewers:
    description: 'Add reviewers to the pull-requests. Separate items by comma.'
    required: false
    default: ''
  directory:
    description: 'Directory which will be scanned.'
    required: false
    default: ''
  include_subdirectories:
    description: 'Iteratively look for project.clj and deps.edn in the subdirectories.'
    required: false
    default: true
  ignore_dependency:
    description: 'Ignore specific dependencies. Separate items by comma.'
    required: false
    default: ''
  allow_dependency:
    description: 'Allow specific dependencies. Separate items by comma.'
    required: false
    default: ''
  local_dependency:
    description: 'Install maven jars to the local repository cache. Separate items by comma.'
    required: false
    default: ''
  summary:
    description: 'Print a human-friendly workflow summary.'
    required: false
    default: true
  verbose:
    description: 'Verbose output.'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'